/* Generated by hand for dsh-edit-resend — Client Remote contribution. */
import { z } from "zod";

const editResendEditParameterSchema = z.object({
  "sessionId": z.string(),
  "turn": z.number().int().nonnegative(),
  "text": z.string(),
}).readonly();

const editResendEditResultSchema = z.union([
  z.object({
    "ok": z.literal(true).readonly(),
    "sessionId": z.string().readonly(),
  }).readonly(),
  z.object({
    "ok": z.literal(false).readonly(),
    "error": z.string().readonly(),
    "message": z.string().readonly().optional(),
    "sessionId": z.string().readonly().optional(),
  }).readonly(),
]);

const editResendGetTextParameterSchema = z.object({
  "sessionId": z.string(),
  "turn": z.number().int().nonnegative(),
}).readonly();

const editResendGetTextResultSchema = z.union([
  z.object({
    "ok": z.literal(true).readonly(),
    "text": z.string().readonly(),
  }).readonly(),
  z.object({
    "ok": z.literal(false).readonly(),
    "error": z.string().readonly(),
    "message": z.string().readonly().optional(),
  }).readonly(),
]);

const editResendUnarchiveParameterSchema = z.object({
  "sessionId": z.string(),
}).readonly();

const editResendUnarchiveResultSchema = z.union([
  z.object({
    "ok": z.literal(true).readonly(),
  }).readonly(),
  z.object({
    "ok": z.literal(false).readonly(),
    "error": z.string().readonly(),
    "message": z.string().readonly().optional(),
  }).readonly(),
]);

export const TYPERT_REMOTE = {
  package: "dsh-edit-resend",
  descriptors: [
    {
      id: "dsh-edit-resend#editResend/edit",
      service: "editResend",
      namespace: "editResend",
      method: "edit",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-edit-resend/types#EditResendRequest",
            schema: editResendEditParameterSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-edit-resend/types#EditResendResult",
        schema: editResendEditResultSchema,
      },
      sourceLocation: { "file": "lib/index.js", "line": 47, "column": 2 },
    },
    {
      id: "dsh-edit-resend#editResend/getText",
      service: "editResend",
      namespace: "editResend",
      method: "getText",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-edit-resend/types#EditResendGetTextRequest",
            schema: editResendGetTextParameterSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-edit-resend/types#EditResendGetTextResult",
        schema: editResendGetTextResultSchema,
      },
      sourceLocation: { "file": "lib/index.js", "line": 47, "column": 2 },
    },
    {
      id: "dsh-edit-resend#editResend/unarchive",
      service: "editResend",
      namespace: "editResend",
      method: "unarchive",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-edit-resend/types#EditResendUnarchiveRequest",
            schema: editResendUnarchiveParameterSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-edit-resend/types#EditResendUnarchiveResult",
        schema: editResendUnarchiveResultSchema,
      },
      sourceLocation: { "file": "lib/index.js", "line": 47, "column": 2 },
    },
  ],
};

export default TYPERT_REMOTE;
