/* Generated by hand for dsh-edit-resend — Host Typert manifest. */
import { z } from "zod";

const editResendEditParameterSchema = z.object({
  "sessionId": z.string(),
  "turn": z.number().int().nonnegative(),
  "text": z.string(),
}).readonly();

const editResendEditResultSchema = z.union([
  z.object({
    "ok": z.literal(true).readonly(),
    "sessionId": z.string().readonly(),
  }).readonly(),
  z.object({
    "ok": z.literal(false).readonly(),
    "error": z.string().readonly(),
    "message": z.string().readonly().optional(),
    "sessionId": z.string().readonly().optional(),
  }).readonly(),
]);

const editResendGetTextParameterSchema = z.object({
  "sessionId": z.string(),
  "turn": z.number().int().nonnegative(),
}).readonly();

const editResendGetTextResultSchema = z.union([
  z.object({
    "ok": z.literal(true).readonly(),
    "text": z.string().readonly(),
  }).readonly(),
  z.object({
    "ok": z.literal(false).readonly(),
    "error": z.string().readonly(),
    "message": z.string().readonly().optional(),
  }).readonly(),
]);

export const TYPERT = {
  package: "dsh-edit-resend",
  face: "host",
  schemas: [
    {
      name: "EditResendRequest",
      schema: editResendEditParameterSchema,
    },
    {
      name: "EditResendResult",
      schema: editResendEditResultSchema,
    },
    {
      name: "EditResendGetTextRequest",
      schema: editResendGetTextParameterSchema,
    },
    {
      name: "EditResendGetTextResult",
      schema: editResendGetTextResultSchema,
    },
  ],
  invocations: [
    {
      id: "dsh-edit-resend#editResend/edit",
      service: "editResend",
      namespace: "editResend",
      method: "edit",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-edit-resend/types#EditResendRequest",
            schema: editResendEditParameterSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-edit-resend/types#EditResendResult",
        schema: editResendEditResultSchema,
      },
      sourceLocation: { "file": "lib/index.js", "line": 47, "column": 2 },
    },
    {
      id: "dsh-edit-resend#editResend/getText",
      service: "editResend",
      namespace: "editResend",
      method: "getText",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-edit-resend/types#EditResendGetTextRequest",
            schema: editResendGetTextParameterSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-edit-resend/types#EditResendGetTextResult",
        schema: editResendGetTextResultSchema,
      },
      sourceLocation: { "file": "lib/index.js", "line": 47, "column": 2 },
    },
  ],
  model: {
    "services": [
      {
        "description": "Edit-and-resend Remote service: forks a child session from a user message's turn and resends edited text.",
        "summary": "Edit-and-resend Remote service.",
        "tags": [],
        "jsDoc": "/**\n * Edit-and-resend Remote service.\n */",
        "key": "editResend",
        "exportName": "EditResendService",
        "members": [
          {
            "kind": "method",
            "name": "edit",
            "signature": "@Remote('edit') async edit(request: EditResendRequest): Promise<EditResendResult>",
            "summary": "Re-send an edited user message by forking a child session from its turn.",
            "jsDoc": "/**\n * Re-send an edited user message.\n */"
          },
          {
            "kind": "method",
            "name": "getText",
            "signature": "@Remote('getText') async getText(request: EditResendGetTextRequest): Promise<EditResendGetTextResult>",
            "summary": "Read the user input text of a completed turn.",
            "jsDoc": "/**\n * Read the user input text of a completed turn.\n */"
          }
        ],
        "types": [
          {
            "name": "EditResendRequest",
            "declaration": "export interface EditResendRequest {\n    readonly sessionId: string;\n    readonly turn: number;\n    readonly text: string;\n}"
          },
          {
            "name": "EditResendResult",
            "declaration": "export type EditResendResult = { readonly ok: true; readonly sessionId: string } | { readonly ok: false; readonly error: string; readonly message?: string; readonly sessionId?: string };"
          },
          {
            "name": "EditResendGetTextRequest",
            "declaration": "export interface EditResendGetTextRequest {\n    readonly sessionId: string;\n    readonly turn: number;\n}"
          },
          {
            "name": "EditResendGetTextResult",
            "declaration": "export type EditResendGetTextResult = { readonly ok: true; readonly text: string } | { readonly ok: false; readonly error: string; readonly message?: string };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
};

export default TYPERT;
